### ISSUE TITLE
can we use external js module ?

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#112]
i mean: we have many external modules: bootstrap.min.js, jquery, react, sweetalert, summernote...
and i don't want rebuild them with webpack, i't can merge from other file...
i see this article: [noParse](http://www.christianalfoni.com/articles/2014_12_13_Webpack-and-react-is-awesome)

at this time, i import all of them.
`import 'bootstrap/dist/js/bootstrap.min';
...
`
and some time out of memory. #109

**Comment by eXon** [comment]
You could configure your webpack.json file to add those as externals. This would means if you import X, instead of using the file, replace it by some global variable. It would be something like this:

Example:
```json
{
  "externals": {
    "react": "React"
  }
}
```

We already do this when you add Meteor package.

I'll add this to the config to support. You can't yet

They are not going to be loaded more than once in your app so it shouldn't be a memory leak.

**Comment by lyquocnam** [comment]
so we will wait for next release ? ( im not good english :D )
