### ISSUE TITLE
Can we use webpack:webpack in meteor packages?

### ISSUE THREAD

**Issue by veeramarni** [thereactivestack/meteor-webpack#116]
Hi,

I tried to use webpack:webpack in package but it is failing with below error.  The reason i want to use in package is to modularize UI and backend using packages (adding any npm dependencies), which i can plug-in when i need to use any of the created packages. 
How to use it in packages?

```
=> Errors prevented startup:
   
   While processing files with webpack:webpack (for target os.osx.x86_64):
   plugin/WebpackCompiler.js:52:13: You cannot use the webpack compiler inside
   a package (at WebpackCompiler.processFilesForTarget)
   
```

I have tried just using webpack:react package within meteor-package but i also need ES6 modules so i can use something like below

```
import NotifyPopup from './components/NotifyPopup.jsx';
import OnBoardingHeader from './components/OnboardingHeader.jsx';

ComponentsUI = {
    NotifyPopup: NotifyPopup,
    OnBoardingHeader: OnBoardingHeader
};
```

**Comment by eXon** [comment]
webpack:webpack is not working within Meteor packages and I don't think there is a reason to do so.

You don't need to use Meteor packages at all, you can import files anywhere so you shouldn't have a problem organizing a modular structure. You have access to any files (even if it's not in your Meteor project folder!).

Because of that, I don't think there is any value to use webpack within Meteor packages. If you think otherwise let me know why!

**Comment by SachaG** [comment]
Would there be a way to use webpack:webpack with a package-based app like Telescope, where the entirety of the code is contained inside packages?

https://github.com/TelescopeJS/Telescope/tree/nova

The reason for choosing that architecture is to let end users update the codebase with `meteor update`, as well as easily add and remove features, by the way.

**Comment by davidworkman9** [comment]
I would also like to know the answer to SachaG's question. I'm kind of fine with not being able to use webpack inside packages, but then not being able to use the ecmascript package in those packages as well means it looks like I'm in for a large amount of work to migrate to webpack.
