### ISSUE TITLE
error: conflict: two packages included in the app (jsx and webpack:webpack) are both trying to handle *.jsx

### ISSUE THREAD

**Issue by adamwong246** [thereactivestack/meteor-webpack#12]
From what I understand, jsx is included by default  as of Meteor 1.2?
also tried tweaking webpack.conf.js to target some other file extension but it's still trying to process .jsx files. I'd rather not remove jsx from my app- I already depend on it.

How can the 2 be made to play nicely?

**Comment by eXon** [comment]
You simply cannot use both. If you use Webpack, this means it will go through babel for ES6 transpiling. It also supports JSX.

The way Webpack works is it starts from an entry.js file and then go through import / requires. Your files are not all loaded automaticlly.

You can still use React from Meteor. Instead of adding the react package, remove it and add react-runtime and react-meteor-data. jsx is irrelevant with Webpack.

[Go look at the example there.](https://github.com/thereactivestack/kickstart-simple)

**Comment by adamwong246** [comment]
ok, but some more direction would help- I'm trying to use these components https://github.com/jaredly/treed in my meteor app. I'm not trying to build my app with webpack.

Here's some more context https://forums.meteor.com/t/how-to-wrap-a-es6-webpack-ed-react-component-for-atmosphere/11597

:confused:  Am I asking the completely wrong question?
