### ISSUE TITLE
How does meteor-webpack handle TypeScript compilation for client, server and shared with modular architecture

### ISSUE THREAD

**Issue by dbx834** [thereactivestack/meteor-webpack#129]
Hello,

I have a question, or rather two, perhaps three. 

- How do I build differently for client and server?
- How do I share code between client and server?
- How do I build differently this shared code that will use two different Typings (main.d.ts and browser.t.ds)?

Example app, Imagine an app with this directory structure,

> - app
>   - - client
>      - index.html
>      - index.tsx
>   - - server
>      - index.ts
>   - - collections
>      - tasks.ts

The first problem is to build differently for client and server. And, the second problem is to share the code between client and server. How is this possible with the current setup?

I have searched for this elsewhere. Please also see,

- [Using shared classes for single output client and common.js based node.js code](https://github.com/Microsoft/TypeScript/issues/5094)
- [SO: share-a-common-package-between-server-and-client](http://stackoverflow.com/questions/32680943/share-a-common-package-between-server-and-client)
- [SO: sharing-typescript-classes-between-client-and-server](http://stackoverflow.com/questions/35796604/sharing-typescript-classes-between-client-and-server)

I might be missing something very obvious here. Are you already doing this? If so, how?

Thanks

**Comment by eXon** [comment]
[Meteor forums](https://forums.meteor.com) is a better place for questions like that.

Here is a short answer:

You have a different entry file for your server and your client. It is defined in your package.json file like this:
```json
{
  "name": "project-name",
  "main": "src/server.js",
  "client": "src/client.js"
}
```

It means instead of loading ALL the js files, it will start at the entry point and then you can import code that is shared between both.

You can look at the [kickstart projects](https://github.com/thereactivestack/kickstart) to understand better how this all work together.
