### ISSUE TITLE
Meteor build error

### ISSUE THREAD

**Issue by feit** [thereactivestack/meteor-webpack#133]
when i run `meteor build ../build_dir --server localhost:3000`, it throw
```js
Errors prevented bundling:
While processing files with webpack:webpack (for target os.osx.x86_64):
fs.js:666:18: ENOENT, no such file or directory
'/Users/feit/codes/cube/node_modules/lodash._getnative/'
at Object.fs.readdirSync (fs.js:666:18)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:655:21)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:653:83)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at compile (packages/webpack:webpack/plugin/WebpackCompiler.js:589:9)
at runWebpack (packages/webpack:webpack/plugin/WebpackCompiler.js:265:5)
at WebpackCompiler.processFilesForTarget
(packages/webpack:webpack/plugin/WebpackCompiler.js:112:5)
```

**Comment by dpacmittal** [comment]
I have a similar error on Meteor 1.3

```
fs.js:666:18: ENOENT, no such file or directory
'/home/dpac/projects/testproject/app-beta/node_modules/ansi-regex/'
at Object.fs.readdirSync (fs.js:666:18)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:655:21)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:653:83)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at compile (packages/webpack:webpack/plugin/WebpackCompiler.js:589:9)
at runWebpack (packages/webpack:webpack/plugin/WebpackCompiler.js:265:5)
at WebpackCompiler.processFilesForTarget
(packages/webpack:webpack/plugin/WebpackCompiler.js:112:5)
```

I think its looking for files in wrong directory. In my particular error, `ansi-regex` exists inside webpack-hot-middleware/node_modules/ansi-html/node_modules/ansi-regex. I guess it's messing up somewhere when processing nested dependencies. The versions I'm using :

```
webpack:assets@1.0.1
webpack:core-config@1.0.1
webpack:css@1.1.1
webpack:npmworkaround@1.0.0
webpack:react@1.1.4
webpack:reload@1.0.0
webpack:webpack@1.0.12
```

**Comment by tokn136** [comment]
Same here.
I tried to catch the readdirSync Exception in  WebpackCompiler.js:
`function addNpmPackage(configFile, packageName, currentPath = '/', addedPackages) {
  const folder = CWD + '/node_modules/' + packageName + currentPath;
  let files = [];
  try {
    files = _fs.readdirSync(folder);
  } catch (exception) {
    console.log(exception);
  }`
There is a long list of modules that the compiler tries to read from the _node_modules_ directory but fails to do so.
@eXon Could it be that the WebpackCompiler doens't require these _node_modules_ but only tries to read them?

**Comment by bensventures** [comment]
I have been experiencing the same issue since I updated to Meteor@1.3 and webpack:webpack 1.0.12. Running the app with `meteor run` works as well as running in production mode. But building does not and consistently fails after between 5 and 15min of `Processing files with webpack:webpack`

My first feeling was that webpack was trying to bundle everything it found in a require for the server bundle and so tried to bundle everything in the `node_modules` directory. I tried to exclude the `node_modules` folder using `webpack-node-externals` without success so it's probably something else.

More info in case it might be useful. I am not using the packages for sass, react, etc. Because I was using an older version of webpack:webpack I have kept the `webpack.conf.js` config files. I do use React, Sass and PostCss but they are all configured manually in the configs. I did try to use the packages but had some errors and couldn't get the app to run so reverted to configs.

**Comment by MasterAM** [comment]
I don't know if it is related, but I have experienced slowness (and bulkness) in builds since upgrading to Meteor v1.3.

When I `meteor build`, the bundle takes some 30 mins to build and results in 800+MB bundle directory.
`/bundle/programs/server/npm` is the lion's share (740MB), of which various babel modules take 400+ MB. I am not sure whether it is normal, but compared to ~180MB bundle from a Meteor + Cordova build, it seems so.

The codebase is not particularly large (~5k `.js`+`.jsx` LOC) and I don't think that I am using anything exotic.

As it is getting really late here, I will compare it to a Meteor v1.2 build tomorrow and report back.

**Comment by mydearxym** [comment]
same problem with [kickstart-meteor-react-router](https://github.com/thereactivestack/kickstart-meteor-react-router) when i run `meteor build ../output`

just install the missing npm packages and you are good to go (it takes me all afternoon ...)

```js
{
  "name": "kickstart-meteor-react-router",
  "private": "true",
  "version": "1.0.0",
  "description": "Kickstart a project with Meteor, React and react-router fast!",
  "main": "src/server.js",
  "browser": "src/client.js",
  "dependencies": {
    "amdefine": "^1.0.0",
    "base62": "^1.1.0",
    "react": "~0.14.8",
    "react-addons-create-fragment": "^0.14.8",
    "react-addons-css-transition-group": "^0.14.8",
    "react-addons-linked-state-mixin": "^0.14.8",
    "react-addons-perf": "^0.14.8",
    "react-addons-pure-render-mixin": "^0.14.8",
    "react-addons-test-utils": "^0.14.8",
    "react-addons-transition-group": "^0.14.8",
    "react-addons-update": "^0.14.8",
    "react-dom": "^0.14.8",
    "react-mixin": "^3.0.3"
  },
  "devDependencies": {
    "acorn": "^3.0.4",
    "asap": "^2.0.3",
    "ast-types": "^0.8.16",
    "babel": "^6.3.26",
    "babel-core": "^6.3.26",
    "babel-loader": "^6.2.0",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-plugin-react-transform": "^2.0.0",
    "babel-plugin-syntax-flow": "^6.5.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.2",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-runtime": "^6.6.1",
    "balanced-match": "^0.3.0",
    "brace-expansion": "^1.1.3",
    "commander": "^2.9.0",
    "commoner": "^0.10.4",
    "concat-map": "0.0.1",
    "core-js": "^2.2.1",
    "css-loader": "^0.23.0",
    "defined": "^1.0.0",
    "detective": "^4.3.1",
    "encoding": "^0.1.12",
    "envify": "^3.4.0",
    "esprima": "^2.7.2",
    "esprima-fb": "^15001.1001.0-dev-harmony-fb",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^0.9.1",
    "fbjs": "^0.8.0-alpha.3",
    "file-loader": "^0.8.5",
    "glob": "^7.0.3",
    "graceful-fs": "^4.1.3",
    "graceful-readlink": "^1.0.1",
    "iconv-lite": "^0.4.13",
    "inflight": "^1.0.4",
    "inherits": "^2.0.1",
    "is-stream": "^1.0.1",
    "isomorphic-fetch": "^2.2.1",
    "js-tokens": "^1.0.3",
    "jstransform": "^11.0.3",
    "loose-envify": "^1.1.0",
    "minimatch": "^3.0.0",
    "minimist": "^1.2.0",
    "mkdirp": "^0.5.1",
    "node-fetch": "^1.4.1",
    "object-assign": "^4.0.1",
    "once": "^1.3.3",
    "path-is-absolute": "^1.0.0",
    "private": "^0.1.6",
    "promise": "^7.1.1",
    "q": "^1.4.1",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "recast": "^0.11.3",
    "redbox-react": "^1.2.0",
    "smart-mixin": "^1.2.1",
    "source-map": "^0.5.3",
    "style-loader": "^0.13.0",
    "through": "^2.3.8",
    "ua-parser-js": "^0.7.10",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.9",
    "webpack-hot-middleware": "^2.4.1",
    "whatwg-fetch": "^0.11.0",
    "wrappy": "^1.0.1"
  }
}
```

**Comment by menelike** [comment]
I think that the problem is located in the function [addNpmPackage](https://github.com/thereactivestack/meteor-webpack/blob/e12caaa483061d7771a95b587199131793a9e1bb/packages/webpack/plugin/WebpackCompiler.js#l653-l669)

This function is meant to be recursive, 

`readPackageJson(configFile, folder + '/package.json', addedPackages);`

but the path always starts from `CWD` and not from the last directory scope:

`const folder = CWD + '/node_modules/' + packageName + currentPath;`

**Comment by darkadept** [comment]
I'm having the same problem. Is there a temporary workaround for deploying in the meantime?

**Comment by MasterAM** [comment]
Reporting back.
In order to test things, I used a fresh (physical) machine with Ubuntu 14.04.3.

I installed Meteor and Node v0.10.4x and checked out my repository.
I created 3 worktrees:
- webpack + 1.3
- webpack + 1.2.1
- standard Meteor

## WebPack + 1.3

This time, attempting to build using v1.3 + Webpack gave me an error similar to the one reported:
```
meteor build ~/webpack-prod-build
Errors prevented bundling:                                                         
While processing files with webpack:webpack (for target os.linux.x86_64):
fs.js:666:18: ENOENT, no such file or directory
'/home/alon/src/(...)/worktree-demo-server/node_modules/gregorian-calendar/'
at Object.fs.readdirSync (fs.js:666:18)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:655:21)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:653:83)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at compile (packages/webpack:webpack/plugin/WebpackCompiler.js:589:9)
at runWebpack (packages/webpack:webpack/plugin/WebpackCompiler.js:265:5)
at WebpackCompiler.processFilesForTarget (packages/webpack:webpack/plugin/WebpackCompiler.js:112:5)
```

## WebPack + 1.2.1
Had to downgrade some packages, obviously.

Got the same error when building, although it ran just fine.

`gregorian-calendar` is a dependency of another dependency (`antd`) which is not a top-level dependency of my project.

I believe it happens in the linking stage. When compiling, the WebPack compiler reads all of the assets to the `configFile` object under the `.webpack/` path, but when linking it seems to be looking for the assets directly in the `node_modules` directory. I only made a shallow inspection, so take it with a grain of salt.

## Standard Meteor build

The migration back to vanilla Meteor was not too difficult, but did require some substantial changes, so I list them in short as a reminder and reference:
- rename `src` to `imports`
- add client and server entry points in the respective dirs. They simply import the original entry points.
- change packages to `ecmascript` (and `less`, in my case)
- create a main `.less` file which imports other less files (now in `imports`) and remove direct imports from `.jsx`.
- move `css` files from `imports` to `client`.

This took a bit under 6 minutes to build and resulted in an 82MB gzipped bundle. 
The build part of the Galaxy deployment took even less.

**Comment by darkadept** [comment]
I'm not sure if this is all related or not, but I was getting a problem during build about missing `fsevents` module from my `node_modules` dir. I'm on linux (ubuntu 15.10, node 5.10.0, npm 3.8.3).

`fsevents` is only for Mac apparently. It shows as an optional dependency of the `semantic-ui` package I'm using. Luckily, `semantic-ui` compiles to a separate folder, so I can remove it during build.

I had to `npm r semantic-ui --save` and then `meteor build ../output`.

I guess webpack:webpack shouldn't be trying to include optional dependencies?

**Comment by fignuts** [comment]
I am also having this issue. Project runs fine but cordova builds and heroku builds fail with ENOENT, no such file or directory

**Comment by dpacmittal** [comment]
Anyone got any workarounds? I have a deployment to do and I don't want to re-setup everything :/

**Comment by bensventures** [comment]
Here is an idea for a workaround: 
* downgrade to webpack:webpack 0.4.4 `meteor add webpack:webpack@0.4.4`
* delete the `node_modules` folder inside `.meteor/local/webpack-npm`
* do a simlink to Meteor's `node_modules` in the root of your project: `ln -s projectpath/node_modules projectpath/.meteor/local/webpack-pm/node_modules`
* Revert to using `webpack.conf.js` files for Webpack conf. Don't forget to add the entry points also to those. (like you were doing in 0.4.4 if you were using it back then)
* build

This seems to kind of work for me. The build does not stop in the middle but does fail when creating the iOS xcode project for some reason. I haven't tried deploying, use at your own risks.

**Comment by dpacmittal** [comment]
Downgraded to 0.4.4 to temporarily do the deployments.

**Comment by mzugn** [comment]
I switched my app to this package because I was sick of Meteor's ridiculous rebuild times and lack of HMR. Now that's solved, but I can't deploy anymore unless I clone this package and add in that try-catch mentioned. I guess it's all about tradeoffs :smile:

**Comment by menelike** [comment]
This is my current whacky solution which of course does not deal with edge cases. It replaces [these two functions](https://github.com/thereactivestack/meteor-webpack/blob/e12caaa483061d7771a95b587199131793a9e1bb/packages/webpack/plugin/WebpackCompiler.js#l636-l670)

```
function readPackageJson(configFile, jsonFile, addedPackages) {
  let packageJson;

  try {
    packageJson = JSON.parse(_fs.readFileSync(jsonFile));
  } catch(e) {}

  if (packageJson && packageJson.dependencies) {
    for (let packageName in packageJson.dependencies) {
      if (addedPackages.indexOf(packageName) < 0) {
        addedPackages.push(packageJson);
        let tail = '/node_modules/' + packageName + '/';
        try {
          addNpmPackage(configFile, packageName, _path.dirname(jsonFile) + tail, addedPackages);
        } catch(e) {
          try {
            addNpmPackage(configFile, packageName, CWD + tail, addedPackages);

          } catch(e) {

          }
        }
      }
    }
  }
}

function addNpmPackage(configFile, packageName, currentPath, addedPackages) {
  const files = _fs.readdirSync(currentPath);

  files.forEach(file => {
    if (_fs.statSync(currentPath + file).isDirectory()) {
      addNpmPackage(configFile, packageName, currentPath + file + '/', addedPackages);
    } else {
      configFile.addAsset({
        path: '.webpack/node_modules/' + packageName + currentPath + file,
        data: _fs.readFileSync(currentPath + file)
      });
    }
  });

  // Look for dependencies
  // we only need to go deeper in case the current path comes from node_modules
  readPackageJson(configFile, currentPath + '/package.json', addedPackages);
}
```

Please do not rely on this, this *might* help you, but is really a quick hack which needs to be solved the right way.

**Comment by feit** [comment]
:/

**Comment by feit** [comment]
@eXon Please Fix This :)

**Comment by lyquocnam** [comment]
mr @eXon have private project so we need wait for him :3 @feit

**Comment by lyquocnam** [comment]
i think this work https://github.com/thereactivestack/meteor-webpack/issues/150

**Comment by FGM** [comment]
The suggested patch, along with an upgrade of webpack from 1.12.14 to 1.13.0, solved the issue for us.

**Comment by menelike** [comment]
@FGM great! FYI, uglify might need to be disabled, see https://github.com/thereactivestack/meteor-webpack/issues/140#issuecomment-214775111

**Comment by FGM** [comment]
Yes I saw that issue, but it turned out not to be necessary with your patch applied, possibly because it is more complete than the simple try/catch on #140, so I did not comment that line.

**Comment by mzugn** [comment]
Thanks @FGM. For me the forked version is causing even longer build times, I don't know exactly how much because I killed it after half an hour, it seemed it wouldn't fail though. The solution for me is still the pure try-catch one, it actually finishes the build (~15 mins). This package really needs some attention to be usable again, this also goes for dev-mode recompilation of server-side code, because that too takes considerable time, but I'm kind of sure that issue is related to this and what's going on in WebpackCompiler.js.

**Comment by menelike** [comment]
@mzugn imho the horrible server build time is caused by the quick fix where a lot more files than actually needed are added as assets.

In my current project HMR + Babel saved us hell more time than sticking to the slightly faster default meteor build.

**Comment by mzugn** [comment]
@menelike You're right, HMR does save a lot of time and I don't actually build that often. I actually also use TypeScript so that adds a bit to refresh time but it's still awesome. One thing I noticed though is that even though webpack does the hot reload almost instantly, Meteor itself picks up the changed files and restarts the server, which breaks the connection to the client for like 10 seconds. That's pretty weird, I thought webpack handles dev mode with a dev server and Meteor doesn't get to do its usual stuff. I haven't read the code though so this might not be correct.

**Comment by eXon** [comment]
What is the NPM version you are using? 

I'm on v3.6.0 and it works fine. It might be because NPM is much smarter now about saving the NPM dependencies as flat as possible. It's not nested like before unless it really needs to.

**Comment by eXon** [comment]
I've fixed it in the last version. It's too bad we need to bundle everything every time we do a build. I know it's slow but there is not much we can do about it :/

**Comment by feit** [comment]
After upgrade npm to v3.8.6, no error throw :)

**Comment by dpacmittal** [comment]
@eXon How can we upgrade npm? Don't we have to use the node packaged with meteor which is still on 0.10.43 (to avoid issues with node-sass), therefore making npm also un-upgradable?

**Comment by menelike** [comment]
I'm not sure if `v3.8.6` should be considered. According to https://github.com/meteor/meteor/pull/5567#issuecomment-214913263 `v2.14.22` is advised. I guess that benjamin hat valid reasons not to use v3.x,though I'm not sure if this is also valid when webpack is is in charge.

**Comment by eXon** [comment]
@menelike I has been fixed no matter what NPM version you are using.

**Comment by eXon** [comment]
It seems like Meteor is bundling devDependencies. This is so wrong. You can follow the bug issue there: https://github.com/meteor/meteor/issues/6836

I hope it will get fixed soon.

**Comment by menelike** [comment]
@eXon 
Glad you found a new solution with https://github.com/thereactivestack/meteor-webpack/commit/96f08a97880d8d4ebcc461cd47c0e18b0a72bfb4, imho this was the weakest point of this project. This should work way better with coming meteor updates.

Good catch on the bundling devDependencies, this explains a lot, thanks for sharing.
