### ISSUE TITLE
Any plans on moving into Webpack v2?

### ISSUE THREAD

**Issue by chompomonim** [thereactivestack/meteor-webpack#174]
Webpack 2 has many cool features, maybe it's time switch into it?
https://gist.github.com/sokra/27b24881210b56bbaff7

**Comment by gsabran** [comment]
+1

**Comment by rvetere** [comment]
woul be awesome! +1

**Comment by eXon** [comment]
It's still in beta. I'll need to take a look if it's stable enough and then we'll make a meteor-webpack 2.0 :)

**Comment by eXon** [comment]
I'll close this because Webpack 2 is not going to be released soon. There is no recent update on that matter.

This was there reaction to the question almost 1 year ago ;)

![soon](https://camo.githubusercontent.com/7bb68ff9b9433da10b1ce317d93b17a2a17c8ab7/687474703a2f2f692e696d6775722e636f6d2f43307a714650782e6a7067)
