### ISSUE TITLE
http://localhost:3500/assets/web.js

### ISSUE THREAD

**Issue by squeal** [thereactivestack/meteor-webpack#198]
Spent a day trying to make webpack not insist on this. No success.
ROOT_URL is ignored, webpack config (a whole hell of its own) is ignored.
Starting to drive me nuts.
And please don't suggest that I run with production flag, that's not the point.

**Comment by eXon** [comment]
What are you trying to accomplish? I need context to understand your problem.

**Comment by Zaiban** [comment]
I had the problem also when attempting to use BrowserSync. By using it in proxy mode it works fine otherwise, but when trying to access the site in other devices outside of localhost, the app loads other files fine but still tries to access localhost:3500/assets/web.js and obviously fails.

BrowserSync seems like the easiest way to test my app in IE and other browsers that cant be installed on Linux, so it is a bummer I cant do that with meteor-webpack.

**Comment by Kyle-Ferrara** [comment]
How to start a localhost server on my leptop to test a site or eccess a site ... (I mean can I access 
any site locally?)
