### ISSUE TITLE
Cannot use react 14 with meteor-webpack

### ISSUE THREAD

**Issue by petrgazarov** [thereactivestack/meteor-webpack#212]
I'm not sure if this is a usage question or a bug, but here is the problem I'm having:

Using Meteor 1.3 + meteor-webpack + react
Trying to use react 14, so I put that version in my `package.json` file
Running `meteor` updates my `package.json` react version to 15.

Seems like `packages/react/webpack.config.js` requires dependency react 15. Is there a way around this or do I have to downgrade `meteor-webpack` version?

**Comment by rvetere** [comment]
There's not truly a way around it - simplest solution would be to upgrade your stack now to react 15 as you should anyways sooner or later (better sooner ;))

But a workaround i can propose is... Checkout the complete "meteor-webpack" project and pick from the "packages" folder the one called "react".

Now go to your own project, and create a folder in your project-root called "packages". Now copy-paste the "react" folder in there.

After a restart of meteor - he will pickup this single package "react" from your local folder instead of the official one from atomosphere.

Now you can modify the "webpack.config.js" in the react folder to fullfill your needs. How this is looking exactly? I have an example project flying around with such customization: https://github.com/rvetere/kickstart-meteor-react-router/tree/next

**Comment by eXon** [comment]
I'm sorry but you'll have to upgrade your React version. Shouldn't be too much hassle.
