### ISSUE TITLE
Client code change triggers server rebuild when code not in client folder

### ISSUE THREAD

**Issue by djules75** [thereactivestack/meteor-webpack#234]
If you change some client code that is not in a folder named client, then HMR kicks in but the server code is also rebuild/reloaded.

This is easy to reproduce starting from the kickstart-meteor-react-router sample project.
If you rename TodoApp/client to TodoApp/ui, then every time you make a change to one of the react component, HMR works but the server code is also rebuild (which means you can't do a page refresh immediately if you need to).

Without webpack:webpack, meteor correctly identifies that the change is client only and doesn't trigger a server reload.

The easy workaround is of course to put the relevant code in my app in a client folder, but it took me some time to found the origin of the problem.

By the way, having HMR working is really awesome, thanks for your work.

**Comment by focused** [comment]
I think it is not the issue, it is by design of this package. You just put client code in a "src/CoreApp/client" folder and subfolders.

**Comment by mzugn** [comment]
You might have a "lib" folder where you store various stuff, for server, client or both. One of the benefits of having webpack is that it knows your dependency tree, so it can actually know that the code you changed is imported only from the client so it should be handled as a client-only change through the webpack dev server, skipping any Meteor rebuilds or restarts. There's no reason for this to not be the case.

I see this as a completely plausible scenario, since one would assume that by using webpack, you actually get rid of most of the Meteor folder-naming rules, and there's no reason to force placement conventions anymore. If I specify my entry point for the client in package.json, I except the system to handle the client dependency tree uniformly without regards to where individual files are.

**Comment by eXon** [comment]
Their is not much we can do about it. Meteor is triggering it and Webpack has no control over it. Make sure to keep all your React code within a client folder.
