### ISSUE TITLE
"no window object present" error when using braintree npm package.

### ISSUE THREAD

**Issue by samcorcos** [thereactivestack/meteor-webpack#26]
I'm getting an error when I add the braintree npm package to my server configuration. I've managed to get it to work using meteorhacks:npm/Meteor.npmRequire and I got it to work using a simple node app, but I can't seem to get it to work with webpack:webpack. Not sure what I'm missing.

The error makes me think that I need to run it in the client, but it's definitely server code.

Here's the repo to reproduce the error:
https://github.com/samcorcos/braintree

**Comment by eXon** [comment]
It is because you cannot bundle a server package within webpack.packages.json. If it has to be run on the server, you have to use `meteorhacks:npm`. The reason is simple: I don't want to send every NPM modules to the server when deploying. It is causing a lot of problems. Instead, webpack.packages.json contains the NPM modules I can bundle and packages.json contains NPM module that are run on the server.

**Comment by samcorcos** [comment]
That makes sense! Thanks. I suppose I didn't understand what it means to "execute binary at runtime".
