### ISSUE TITLE
"webpackJsonp is not defined" when running in production

### ISSUE THREAD

**Issue by samcorcos** [thereactivestack/meteor-webpack#28]
When I run `$ meteor run --production`, I get the following error:

```
webpackJsonp is not defined
```

This is probably a simple fix, but I don't know what I'm missing.

**Comment by eXon** [comment]
This means you are missing your common chunk. It has to be loaded at first. This is taken care of by react-router-ssr if you're using a chunk called common (just like in the hugeapp example).

**Comment by eXon** [comment]
If you're still having problems with this you can re-open this issue.

**Comment by john-osullivan** [comment]
I have my `entry/client/webpack.conf.js` identical to the one in kickstart-hugeapp, using the same calls on `webpack.optimize.CommonsChunkPlugin`:

'''
if (process.env.NODE_ENV === 'production') {
  plugins.push(new ExtractTextPlugin('style.css', {allChunks : true}));
  cssLoader = ExtractTextPlugin.extract('style', 'css?module&localIdentName=[hash:base64:5]');

  if (!Meteor.isCordova){
    plugins.push(new webpack.optimize.CommonsChunkPlugin('common', 'common.web.js'));
  }
} else {
  cssLoader = 'style!css?module&localIdentName=[name]__[local]__[hash:base64:5]';
}
'''

Are there any other reasons I might have this error?  As is, I'm loading both of my site's modules normally (i.e. the way `TodoApp` is loaded immediately, not the way `AdminApp` is loaded by chunks) because I didn't want to fiddle with chunks yet.  Would running the "chunks" code without pushing anything onto the `ChunkCollector` cause a problem?

**Comment by eXon** [comment]
Your common chunk has to be loaded BEFORE the main script. How are you loading them?

**Comment by john-osullivan** [comment]
I'm not quite sure, to be honest.  How are the chunks loaded in `kickstart-hugeapp`?  That's my model here.  In fact, I assumed that the code I linked was loading the chunks --- where am I going wrong?

**Comment by harrysbaraini** [comment]
Same problem here when I deploy to meteor.com

**Comment by john-osullivan** [comment]
I'm not sure about you, @harrysbaraini , but the actual HTML which loads my chunks is being autogenerated.  I presume it's being generated by Meteor-Webpack, although it might be generated by React-Router-SSR.  The autogenerated page has two Javascript script tags on it, it seems like the first one isn't successfully loading everything it should.  Here are the tags, directly copied from my page:

```
<script type="text/inject-data">%7B%22fast-render-data%22%3A%7B%22collectionData%22%3A%7B%22users%22%3A%5B%5B%7B%22_id%22%3A%22yvQjsgW76opkPHMNx%22%2C%22username%22%3A%22rgomez%22%7D%5D%5D%7D%2C%22subscriptions%22%3A%7B%7D%2C%22loginToken%22%3A%22rwtaaLQIiqZL4KTHpqPy_SmBFk_boUVG0j-W81UfH63%22%7D%7D</script>

<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.2.1%22%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Flocalhost%3A3000%2F%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%221c6pyq46a2juev8rw7t%22%2C%22autoupdateVersion%22%3A%224a812971149e355fbf57230bb454911a98b76d69%22%2C%22autoupdateVersionRefreshable%22%3A%22c32ff1a7b4b660a9ab33bcd88450052a42235c27%22%2C%22autoupdateVersionCordova%22%3A%22none%22%7D"));</script>

  <script type="text/javascript" src="/42d42d020fe54bb630f9b5a6bf0223101c7981eb.js?meteor_js_resource=true"></script>
```

The `webpackJsonp` defined error is coming from that last file there.  @eXon , do you think I should focus on debugging within Meteor-Webpack, or is React-Router-SSR a more likely source of this bug?

**Comment by eXon** [comment]
The error "webpackJsonp is not defined" happens when your common chunk is not loaded before your main chunk. If you are using react-router-ssr, are your generated common chunk is named "common"?

**Comment by john-osullivan** [comment]
It looks like I was getting that bug because I commented out the `require('../client/routes') line in `kickstart-hugeapp` which brings the client code into the server when running in production.  When I brought that line back in, I got back to an error I previously had:
```
ReferenceError: jQuery is not defined.
```
I'm doing more debugging now, but as far as I can tell, I only use jQuery in componentDidMount() methods.  Now I'm checking to see if any dependencies use jQuery at the wrong time, but it seems like this is an issue with how things are getting loaded.  The error specifically gets thrown after webpack builds the web/server bundles, when it tries to run the server bundle.

**Comment by john-osullivan** [comment]
Okay, I've eliminated all dependencies which might have used jQuery upon initial render.  The stack trace no longer contains reference to any non-React packages, it now seems to be an issue with "animationIterationCount"...

![image](https://cloud.githubusercontent.com/assets/3820981/13331715/b24171f6-dbcc-11e5-95b6-552df8119c5d.png)

**Comment by harrysbaraini** [comment]
@john-osullivan In my case, HTML isn't autogenerated. To solve it, I removed the code which loads chunks, but I think it's not the right way.

**Comment by perrohunter** [comment]
@eXon how do I make sure my common chunks are getting loaded in the right order?

I'm loading them this way

```
new webpack.optimize.CommonsChunkPlugin({
       name: ['polyfills', 'vendor','merchant'].reverse()
}),
```

but still I get `Uncaught ReferenceError: webpackJsonpac__name_ is not defined`
