### ISSUE TITLE
meteor package with ecmascript dependency breaks everything

### ISSUE THREAD

**Issue by lusilva** [thereactivestack/meteor-webpack#44]
I'm using orionjs (orionjs.org) as a CMS for a meteor project along with this package, but orionjs:core package depends on ecmascript. When I add the package, I get an error saying that both packages (ecmascript and webpack) are trying to handle *.js files.

I'm unfamiliar with webpack, but is there a workaround for packages with ecmascript as a dependency? maybe exclude the meteor package in the webpack config?

**Comment by Zodiase** [comment]
I think if the package is only "use"ing ecmascript, it should not affect the app that's using webpack. Because "use"ing a package in a package does not expose that package being used to the app. Unless that package is "imply"ing ecmascript which will expose ecmascript to the app. In that case, there is nothing this package can do to undo the "imply"ing. I have a feeling that the package you are using that's "imply"ing ecmascript probably should not have done that. To me there is no reason a package should enforce the app to use ecmascript package.

**Comment by Zodiase** [comment]
And I found here: https://github.com/orionjs/orion/blob/master/packages/base/package.js that indeed this package is implying ecmascript, which is pointless to me.

**Comment by lusilva** [comment]
Yeah, I got around this by downloading the package locally and removing the ecmascript dependency. Everything works fine now.

**Comment by eXon** [comment]
I'm sorry about that. You can't have 2 compiler on the same file extension (.js, .jsx, ...). Meteor build system doesn't allow it so we can't have ecmascript and webpack at the same time.

Hopefully it is more clear to you :)
