### ISSUE TITLE
How will Meteor 1.3 affect this package?

### ISSUE THREAD

**Issue by rclai** [thereactivestack/meteor-webpack#48]
Will there be things that break?
Are you still going to maintain this?

**Comment by casperan** [comment]
I've followed the next branch

my concerns are, it looks like
- it continues to rely on meteor react-packages, rather than react from npm
- it uses meteor packages to be helpful, address peoples concerns with how difficult it is to configure webpack

Personally I'd rather it suggests/uses react+babel modules package from npm and suggest configurations for the .babelrc, webpack.conf, package.json files manually for different challenges, and offers the meteor add as an option only for those who wants to be dumbed down

**Comment by eXon** [comment]
Yes Meteor 1.3 is going to be supported, but I will also make sure we are retro-compatible for a while. Ideas are always welcomed.

For the react-packages, I would love to use React from NPM but it will not work with Meteor 1.2. Only 1.3 can use outside NPM packages within Meteor packages. I'm really excited about that but there will be a transition phase.

This is still a work in progress but something will be released in the upcoming weeks. :)

**Comment by casperan** [comment]
1.2 retro-compatibility is understandable, but it calls for a 1.3+ fork/branch :) with direct webpack.conf editing. Anyone else thinking in this direction?

**Comment by eXon** [comment]
I agree. I'll try to think how we cN do that

**Comment by jperl** [comment]
Yeah, we are looking forward to switching to npm react packages -- and would be happy for a major version bump that requires 1.3.

**Comment by jeffshaver** [comment]
Will there be a small upgrade guide since it seems like this would have some changes to what files are needed (i.e. webpack.packages.json)?

**Comment by dagatsoin** [comment]
I have already switched to Meteor 1.3 and I am stuck at styling tools choice.
I think the most reliable way for me is to to use react-css-modules but it uses Webpack.
I just found your package and read a line or two on what you tend to do for Meteor 1.3

What could be the best way for me to use react-css-modules in Meteor 1.3 with Webpack? Would the "Next" branch state be reliable for me?

**Comment by eXon** [comment]
The next branch is the 1.0 version coming up. It's not released yet on Atmosphere but yea, this is going to be reliable.

**Comment by eXon** [comment]
meteor-webpack 1.0 will be 100% compatible with Meteor 1.3 when released on march 1st.
