### ISSUE TITLE
meteor 1.3-beta.11 webpack not reload when change jsx file.

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#89]
i try 2 code line in my Layout.jsx:
`import './style1.styl';`
change to
`import './style2.styl';`
but it not auto reload not working.

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details
```

F5 on browser on work.
i tried  add this on webpack config:
```
  "hotMiddleware": {
    "reload": true
  },
```
but still not wok !

**Comment by lucidprogrammer** [comment]
I have the same issue METEOR@1.3-beta.12. .jsx is a pure function.
"hotMiddleware" : {"reload" : true} does not do any good. Could this be fixed. Alternatively, how do i disable the HMR itself 


[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.

**Comment by lyquocnam** [comment]
ya, we must F5 usually. waiting for author about this fix :3

**Comment by lucidprogrammer** [comment]
Looking at the function patchReload() {} in reload.js in webpack:reload, just before the return, there could be a Tracker.autorun which could check if 'modules couldn't be hot updated' and call Reload._reload() ? Hmm not sure how to get that though where my webpack internal knowledge is limited. Any inputs? This is important as with the pure function components, this is happening all the time.

**Comment by eXon** [comment]
@lucidprogrammer Stateless components are not yet supported with hot reload. This is not a Meteor problem. It will be supported in the future.

@lyquocnam Do you have a bigger snippet of code of the .styl hot-reload not working?

**Comment by lyquocnam** [comment]
ya as you say: Stateless components are not yet supported with hot reload.
thanks so much mr @eXon we will wait for next version staleless support.
i like write stateless, it is simple.
